### ISSUE TITLE
generated image samples

### ISSUE THREAD

**Issue by suheey** [deeplearning-wisc/dream-ood#13]
Hi,

I want to check the performance with other models with your generated samples, but i couldnt find samples list on your following link. Could you give us the sample file?

**Comment by d12306** [comment]
hi @suheey , here goes the link to the generated images: https://uwprod-my.sharepoint.com/:f:/g/personal/xdu66_wisc_edu/EnL7GS4mQQxGlRcbWZgnwr0BfFKhPoLkkP463Xo94Hzfgw?e=ULi53j


Sorry for the delay in announcing the generated images because I did not find a free drive with a large storage. The link will expire in 30 days and I will also update the GitHub page, thanks! If you have a suggested free online drive with large storage limits, please don't hesitate to forward it to me!!

**Comment by suheey** [comment]
Heyy,


Thank you for your reply!

Fortunately, I was able to use the embedding information you already posted
on GitHub to easily generate outlier images.

I was also thrilled to be able to reference your excellent research in my
paper!

I've submitted my work to NeurIPS, and if the results turn out well, I'll
also share my research with you! :)


Anyway thank you for sharing the new link. I'll compare it with the images
I generated.

I'm currently working on LLM-based OOD detection research, and it would be
great to have a discussion about it sometime!


Best regards,

2024년 5월 30일 (목) 오전 10:07, Xuefeng Du ***@***.***>님이 작성:

**Comment by d12306** [comment]
hi @suheey , so glad to hear that!! good luck with your neurips submission and thank you for referring our paper!

"
I'm currently working on LLM-based OOD detection research, and it would be
great to have a discussion about it sometime!
"
nice to hear that! just shoot me an email if you want since I will have more time in the summer and later!

Best,
Xuefeng
