### ISSUE TITLE
Text anchors and Outlier image-generation

### ISSUE THREAD

**Issue by Cverchen** [deeplearning-wisc/dream-ood#2]
Hello!
Great work! But i want to konw how to generate the text anchors? Are they generated by CLIP's text encoder? Is this image-text space the same as the original CLIP's image-text space?
Besides, once the pseudo-features are constructed, they will be fed into the diffusion model, which can be found in the "dream_ood" file. Although there is a "load_embedding" function, I didn't see any code on how these embeddings are used to guide image generation.
I look forward to your response.
Thanks!

**Comment by d12306** [comment]
hi, @Cverchen , thanks for the interest in our work! 

We generate the anchors by pulling the corresponding token embeddings in the token embedding table. We do not use the textual embeddings directly from the text encoder in stable diffusion, there are two reasons:

1. directly using the textual embeddings from the text encoder prevents us from utilizing the extrapolation ability of the large text encoder in CLIP (which is used in stable diffusion)
2. we found that directly using the textual embeddings from the text encoder will generate images looking like noise, rather than real images. 

for the loaded embedding, it will be used here https://github.com/deeplearning-wisc/dream-ood/blob/9f677ac890a4f45f3fb92d0b91f25df409be0e6c/ldm/modules/encoders/modules.py#L311 to replace the original token embedding in the stable diffusion.

**Comment by Cverchen** [comment]
Understand！ Thanks for your answering！

**Comment by Cverchen** [comment]
Hi, @d12306 
I want to ask one more question: 
For the token embedding of each category, does it only generate the embeddinganchor of words in this category? But if it is a sentence that will generate a representation similar to (1, 77, 768), how to generate support in the (1, 768) dimension?
Thanks!

**Comment by d12306** [comment]
hi, @Cverchen , great question! In fact, we only replace the token embedding of a single class name/token among the 77 tokens, say "cat", and do not change the other token embeddings in a sentence. 

"And I see the length of used name of category is 1, but if the length becomes two or longer, how the embedding anchor to be generated?"

Unfortunately, dream-ood does not deal with the case in our current experiments that when the class name is tokenized as two or more tokens. But you can certainly do that by learning the text-conditioned latent space conditioned on each one of the two or more token embeddings and then replace the token embeddings in the stable diffusion with the corresponding outlier embeddings. 

This is one disadvantage of the stable diffusion models. since the conditioning vectors has a shape of 77*768 rather than 1*768,  that being said, our general generation framework can be adapted to other text2image diffusion models easily when the conditioning vector has a shape of  1*768. and this can solve the issue smoothly.

**Comment by zjysteven** [comment]
Hi Xuefeng @d12306, maybe I should open a new issue but decided to ask here since the context is related.
https://github.com/deeplearning-wisc/dream-ood/blob/9f677ac890a4f45f3fb92d0b91f25df409be0e6c/ldm/modules/encoders/modules.py#L295
I was wondering why here there are 10k embeddings for each class, but in the paper it says 1k images are generated per class. Is it just because that image generation is costly?

**Comment by d12306** [comment]
> Hi Xuefeng @d12306, maybe I should open a new issue but decided to ask here since the context is related.
> 
> https://github.com/deeplearning-wisc/dream-ood/blob/9f677ac890a4f45f3fb92d0b91f25df409be0e6c/ldm/modules/encoders/modules.py#L295
> 
> 
> I was wondering why here there are 10k embeddings for each class, but in the paper it says 1k images are generated per class. Is it just because that image generation is costly?

yes, pretty much is because of the computational burden. In practice, we might not need that much OOD images

**Comment by allglc** [comment]
Hello,

Thanks for releasing your code. But I did not understand this part:
> We generate the anchors by pulling the corresponding token embeddings in the token embedding table. 

Can you further explain? What is the token embedding table? Maybe you can also release the code used to generate the file `token_embed_in100.npy`?

Thanks!

**Comment by d12306** [comment]
hi @allglc , the token embedding table is from the text encoder of the diffusion models. it is already extracted and stored in the [token_embed_c100.npy](https://github.com/deeplearning-wisc/dream-ood/blob/main/token_embed_c100.npy) and [token_embed_in100.npy](https://github.com/deeplearning-wisc/dream-ood/blob/main/token_embed_in100.npy)
